### PR TITLE
Updates to the script

### PR DESCRIPTION
**Pull request by MBtech**
**Added features**
1. Removed the need to for sudo. The tool are downloaded into the script directory.
2. User now has the option to specify the output directory for the decomipled output.

### CODE REVIEW

**Comment by TheZ3ro** [comment]
Great!

Just a little thing, what's the purpose of replacing `#!/usr/bin/env python3` with `#!/usr/bin/python3`?

I think using `env` is much portable (It's a POSIX component thus found in pretty much every system), 
hard coding the python interpreter path is good on Debian systems (see [debian python policy](https://www.debian.org/doc/packaging-manuals/python-policy/ch-python.html#s-interpreter)) but I think that the key point is don't get Error on users' system.
(maybe users use virtualenv or python is installed in /usr/local/bin/.)

What do you think about? :smile:

**Comment by MBtech** [comment]
You are right, I guess. 
Though using #!/user/bin/env python3 was giving me weird problems on my ubuntu system. 
Apparently there is a problem in the env file that I had. It's messed up because of some other android stuff. Need to look into it.

**Comment by TheZ3ro** [comment]
It's ok, so you can make a new commit to fix that?

When it's ready I will merge the pull request :+1:

**Comment by MBtech** [comment]
Done :)

**Comment by TheZ3ro** [comment]
Thanks, merge done :)

**Comment by MBtech** [comment]
Perfect :D

**Pull request merged**
